apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:3.6
          ports:
          - containerPort: 27017