apiVersion: v1
kind: ReplicationController
metadata:
  name: forntendkiwi
spec:
  replicas: 2
  selector:
    app: forntendkiwi
  template:
    metadata:
      labels:
        app: forntendkiwi
    spec:
      containers:
        - name: forntendkiwi
          image: bywind/flawsweeper-frontend
          ports:
          - containerPort: 8080
